import Head from "next/head"
import styles from "../styles/Home.module.css"
import DrawerCard from "@/components/DrawerCard"
import dynamic from "next/dynamic"
import { ConnectButton } from "@rainbow-me/rainbowkit"
import { Toaster } from "@/components/ui/toaster"

const Map = dynamic(() => import("../components/Map"), {
  loading: () => <p>Loading Map.....</p>,
  ssr: false
})

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Proof of Location Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex flex-col md:flex-row items-center justify-between w-full p-4">
          <ConnectButton />
          <DrawerCard />
        </div>
        <div className="w-full h-[600px] mt-4">
          <Map />
        </div>
      </main>
      <Toaster />
    </div>
  )
}

export default Home
